- name: email
  type: regex
  regex:
    - '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.(?!(?:png|jpg|jpeg|gif|svg|bmp|webp|ico|css|js|json|xml|csv|txt|pdf|doc|docx|xls|xlsx)\b)[a-zA-Z]{2,}'

- name: phone
  type: regex
  regex:
    - '\+?\d[\d\s()\-]{6,}\d'
